Repository Likelion12th-HufsGlobal-Hackathon-team7/FE, pull requests merged in 2024-07, with the labels that each got.

#1 Setting vite
  runWithMate/.eslintrc.cjs
  runWithMate/.gitignore
  runWithMate/README.md
  runWithMate/index.html
  runWithMate/package-lock.json
  runWithMate/package.json
  runWithMate/public/rwmIcon.svg
  runWithMate/src/App.jsx
  runWithMate/src/components/siteButton.jsx
  runWithMate/src/main.jsx
  runWithMate/src/pages/game/gameResult/index.jsx
  runWithMate/src/pages/game/index.jsx
  runWithMate/src/pages/game/settingGame/index.jsx
  runWithMate/src/pages/login/index.jsx
  runWithMate/src/pages/main/index.jsx
  runWithMate/src/pages/mypage/index.jsx
  runWithMate/src/pages/point/index.jsx
  runWithMate/src/pages/siteMap.jsx
  runWithMate/src/routes.jsx
  runWithMate/src/styles/globalstyles.jsx
  runWithMate/src/styles/mobile.jsx
  runWithMate/vite.config.js
Labels: 📝 docs, ✨ feat, 🚚 docs-routh

#2 Setting02
  runWithMate/.babelrc
  runWithMate/.vite/deps/_metadata.json
  runWithMate/.vite/deps/package.json
  runWithMate/index.html
  runWithMate/package-lock.json
  runWithMate/package.json
  runWithMate/src/App.jsx
  runWithMate/src/main.jsx
  runWithMate/src/pages/game/index.jsx
  runWithMate/webpack.config.jsx
Labels: 📝 docs, ✨ feat, 🚚 docs-routh

#3 Setting global
  runWithMate/src/main.jsx
  runWithMate/src/pages/game/index.jsx
  runWithMate/src/styles/globalstyles.jsx
Labels: 📝 docs, 🎨 design

#4 Test login
  runWithMate/index.html
  runWithMate/package-lock.json
  runWithMate/package.json
  runWithMate/public/favicon.png
  runWithMate/public/rwmIcon.svg
  runWithMate/src/assets/images/NoBgIcon.png
  runWithMate/src/components/Header.jsx
  runWithMate/src/pages/login/index.jsx
  runWithMate/src/pages/main/index.jsx
  runWithMate/src/styles/mobile.jsx
  runWithMate/vite.config.js
Labels: 📝 docs, 🎨 design

#6 Design login
  runWithMate/index.html
  runWithMate/src/assets/images/Login.png
  runWithMate/src/assets/images/brainIcon.png
  runWithMate/src/assets/images/gameIcon.png
  runWithMate/src/assets/images/gameMarker.png
  runWithMate/src/assets/images/kakao_login.png
  runWithMate/src/assets/images/pointIcon.png
  runWithMate/src/assets/images/pointMarker.png
  runWithMate/src/components/Header.jsx
  runWithMate/src/components/game/Map.jsx
  runWithMate/src/pages/game/gameResult/index.jsx
  runWithMate/src/pages/game/index.jsx
  runWithMate/src/pages/login/index.jsx
  runWithMate/src/pages/main/index.jsx
  runWithMate/src/pages/test.jsx
  runWithMate/src/routes.jsx
  runWithMate/src/styles/globalstyles.jsx
Labels: 📝 docs, 🎨 design

#7 test:jihee new laptop push test
  runWithMate/src/pages/main/index.jsx
Labels: 🪧 test

#8 Design setting UI 1차
  runWithMate/src/pages/game/settingGame/components/Content.jsx
  runWithMate/src/pages/game/settingGame/components/Lobby.jsx
  runWithMate/src/pages/game/settingGame/components/Player.jsx
  runWithMate/src/pages/game/settingGame/components/Player2.jsx
  runWithMate/src/pages/game/settingGame/components/Setting.jsx
  runWithMate/src/pages/game/settingGame/index.jsx
Labels: 📝 docs, 🎨 design

#10 Feat kakao map
  runWithMate/src/App.jsx
  runWithMate/src/components/Header.jsx
  runWithMate/src/pages/game/gameResult/index.jsx
  runWithMate/src/pages/login/index.jsx
  runWithMate/src/pages/main/index.jsx
  runWithMate/src/pages/test.jsx
  runWithMate/src/styles/mobile.jsx
Labels: 📝 docs, 🎨 design, ✨ feat

#11 Feat kakaomap02
  runWithMate/src/components/game/Map.jsx
  runWithMate/src/pages/game/index.jsx
  runWithMate/src/pages/test.jsx
  runWithMate/src/routes.jsx
Labels: 🎨 design, 🗑️remove, ✨ feat, 🚚 docs-routh

#15 Feat game components
  runWithMate/src/components/game/GameInfo.jsx
  runWithMate/src/components/game/GameRanking.jsx
  runWithMate/src/pages/game/index.jsx
Labels: 📝 docs, ✨ feat, 🚚 docs-routh

#16 Feat kakaomap03
  runWithMate/src/components/game/GameInfo.jsx
  runWithMate/src/components/game/GameRanking.jsx
  runWithMate/src/components/game/Map.jsx
  runWithMate/src/pages/game/index.jsx
Labels: 📝 docs, 🎨 design, ✨ feat

#19 Feat marker
  runWithMate/src/assets/images/dopamineMarker.png
  runWithMate/src/assets/images/gameMarker.png
  runWithMate/src/assets/images/pointMarker.png
  runWithMate/src/components/game/Map.jsx
Labels: 📝 docs, 🗑️remove, ✨ feat

#22 Feat kakao map marker event
  runWithMate/src/components/game/GameInfo.jsx
  runWithMate/src/components/game/Map.jsx
Labels: 🎨 design, ✨ feat

#25 Feat web socket01
  runWithMate/src/components/game/GameInfo.jsx
  runWithMate/src/components/game/Map.jsx
  runWithMate/src/components/game/gameGiveUp/giveup.jsx
  runWithMate/src/hooks/useWebSocket.jsx
  runWithMate/src/pages/main/index.jsx
Labels: 📝 docs, ✨ feat

#27 Feat timeout02
  runWithMate/src/components/Header.jsx
  runWithMate/src/components/game/Map.jsx
  runWithMate/src/hooks/useWebSocket.jsx
  runWithMate/src/pages/game/index.jsx
Labels: 📝 docs, ✨ feat

#30 Feat point page
  runWithMate/public/img/GoodJob.png
  runWithMate/public/img/profile.png
  runWithMate/src/assets/images/cg.png
  runWithMate/src/assets/images/cg2.png
  runWithMate/src/assets/images/cp.png
  runWithMate/src/assets/images/dp.png
  runWithMate/src/assets/images/mg.png
  runWithMate/src/assets/images/mg2.png
  runWithMate/src/assets/images/mp.png
  runWithMate/src/assets/images/pp.png
  runWithMate/src/components/game/GameOver/GameOver.jsx
  runWithMate/src/components/point/CategoryMap.jsx
  runWithMate/src/components/point/MyPointBox.jsx
  runWithMate/src/pages/pointShop/index.jsx
  runWithMate/src/routes.jsx
Labels: 📝 docs, ✨ feat, 🚚 docs-routh, 🪧 test

#32 Feat ws stomp02
  runWithMate/package-lock.json
  runWithMate/package.json
  runWithMate/src/components/point/CategoryMap.jsx
  runWithMate/src/hooks/useStomp.jsx
  runWithMate/src/pages/test.jsx
  runWithMate/src/routes.jsx
Labels: 📝 docs, ✨ feat, 🪧 test

#36 Feat ws stomp
  runWithMate/src/hooks/useStomp.jsx
  runWithMate/src/pages/game/index.jsx
  runWithMate/src/pages/game/settingGame/index.jsx
  runWithMate/src/pages/login/index.jsx
  runWithMate/src/pages/main/index.jsx
Labels: 🚨 fix, 📝 docs, ✨ feat

#43 잘못된 라이브러리 사용 수정, css 조금 수정
  runWithMate/src/components/game/gameResult/GameTimer.jsx
  runWithMate/src/components/point/CategoryMap.jsx
  runWithMate/src/hooks/useStomp.jsx
Labels: 🎨 design, ✏️ chore

#44 Chore img
  runWithMate/.env
  runWithMate/index.html
  runWithMate/public/img/Login.png
  runWithMate/public/img/NoBgIcon.png
  runWithMate/public/img/brainIcon.png
  runWithMate/public/img/gameIcon.png
  runWithMate/public/img/kakao_login.png
  runWithMate/public/img/pointIcon.png
  runWithMate/src/assets/images/GoodJob.png
  runWithMate/src/assets/images/profile.png
  runWithMate/src/components/Header.jsx
  runWithMate/src/components/game/Map.jsx
  runWithMate/src/components/game/gameResult/gameResult.jsx
  runWithMate/src/components/point/MyPointBox.jsx
  runWithMate/src/hooks/useStomp.jsx
  runWithMate/src/pages/login/index.jsx
  runWithMate/src/pages/main/index.jsx
Labels: 📝 docs, ✏️ chore, 🗑️remove, 🚚 docs-routh

#45 Fix map error
  .github/workflows/deploy.yml
  runWithMate/.env
  runWithMate/default.conf
  runWithMate/dockerfile
  runWithMate/index.html
  runWithMate/src/components/game/Map.jsx
  runWithMate/src/pages/main/index.jsx
Labels: 🚨 fix, 📝 docs
